/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author danae
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipa
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuingresar = new javax.swing.JMenuItem();
        jMenumostra = new javax.swing.JMenu();
        jMenumostrar = new javax.swing.JMenuItem();
        jMenuSali = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        jMenu1.setText("ingresar");

        jMenuingresar.setText("ingresar");
        jMenuingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuingresarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuingresar);

        jMenuBar1.add(jMenu1);

        jMenumostra.setText("mostrar");

        jMenumostrar.setText("mostrar");
        jMenumostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenumostrarActionPerformed(evt);
            }
        });
        jMenumostra.add(jMenumostrar);

        jMenuBar1.add(jMenumostra);

        jMenuSali.setText("salir");

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenuSali.add(jMenuSalir);

        jMenuBar1.add(jMenuSali);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuingresarActionPerformed
        // TODO add your handling code here:
        VentanaIngreso ventPrin=new VentanaIngreso();
        ventPrin.setLocationRelativeTo(null);
        ventPrin.setTitle("INGRESO DE DATOS");
        ventPrin.setResizable(false);
        ventPrin.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        ventPrin.setVisible(true);
    }//GEN-LAST:event_jMenuingresarActionPerformed

    private void jMenumostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenumostrarActionPerformed
        // TODO add your handling code here:
                VentanaMostrar ventPrin=new VentanaMostrar();
        ventPrin.setLocationRelativeTo(null);
        ventPrin.setTitle("INGRESO DE DATOS");
        ventPrin.setResizable(false);
        ventPrin.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        ventPrin.setVisible(true);
    }//GEN-LAST:event_jMenumostrarActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuSali;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JMenuItem jMenuingresar;
    private javax.swing.JMenu jMenumostra;
    private javax.swing.JMenuItem jMenumostrar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
